### ISSUE TITLE
condition-handlers always error

### ISSUE THREAD

**Issue by lavirlifiliol** [google/lisp-koans#116]
in `koans/ondition-handlers.lisp`, koans always signals an error, for example
```lisp
(define-test handler-bind
  ;; When a condition is signaled, all handlers whose type matches the
  ;; condition's type are allowed to execute.
  (let ((*list* '()))
    (handler-bind ((my-error #'handle-my-error)
                   (error #'handle-error)
                   (my-serious-condition #'handle-my-serious-condition))
      (signal (make-condition 'my-error)))
    (assert-equal '( :error :my-error) *list*)))
```
this is solved in  `koans-solved/condition-handlers.lisp`

**Comment by phoe** [comment]
Correct, thanks for the catch.

Fixed by #117

**Comment by phoe** [comment]
Let's wait for confirmation that the koans work now before this issue is closed and the PR is merged.

**Comment by lavirlifiliol** [comment]
the PR does fix this, all koans in the file are solveable

**Comment by phoe** [comment]
@lavirlifiliol Thanks for verification!

@Slids Ready to merge.
