### ISSUE TITLE
Special forms: Introduce CASE as well?

### ISSUE THREAD

**Issue by flpa** [google/lisp-koans#52]
Koan "special-forms.lsp" introduces COND and states:

> the cond form is like the c switch statement

In my opinion, CASE is a closer match - at least for types that can be compared via EQL. 
This limitation could be demonstrated by explaining CASE first, showing samples with numbers/keywords and progressing to strings. After showing that case does not suffice for strings, COND is introduced as a more general-purpose special form (similar to C if-else if-else if...)

What do you think?

_Bonus: ECASE might also be of interest for learners._

**Comment by bileschi** [comment]
The student of the koans is assumed to know very little of other
languages.  If there is a simpler path to enlightenment, please offer a
pull request, and it will be considered.

Thank you for your interest in the lisp koans.
-Stan

**Comment by rowanthorpe** [comment]
As the related Pull Request has been merged it seems this issue could be closed - or is there a reason for it staying open? Perhaps because of the mention of ECASE as a bonus?

**Comment by flpa** [comment]
No I think you're right, I'll close the issue 👍
