### ISSUE TITLE
test-reduce-basics instructions are not clear

### ISSUE THREAD

**Issue by astronaut-wannabe** [google/lisp-koans#65]
``` lisp
(define-test test-reduce-basics
    "The reduce function applies uses a supplied
     binary function to combine the elements of a
     list from left to right."
  (assert-equal ___  (reduce #'+ '(1 2 3 4)))
  (assert-equal ___ (reduce #'expt '(2 3 2))))
```

This doc string doesn't really make sense, specifically the "_function applies uses a_" bit.

I was going to open a PR, but I am not actually sure what it is supposed to be. Maybe:

> The reduce function combines the elements of a list, from left to right, by applying a supplied binary function to the list elements

**Comment by bileschi** [comment]
I guess that's a bit easier to understand.  Maybe drop the 'supplied'? Feel free to make a PR.

**Comment by rowanthorpe** [comment]
If the merged commit fixed this adequately it would be good to close the issue, otherwise to add info about what is still needed.

**Comment by Slids** [comment]
Since there's been no update in a few years, I'm guessing the fix was adequate.
