### ISSUE TITLE
CLISP runs tests in reverse order

### ISSUE THREAD

**Issue by ghost** [google/lisp-koans#77]
Running on a fresh version, on CLISP, outputs the following:

> Thinking about ASSERTS
>    TEST-TRUE-OR-FALSE requires more meditation.
> 
> You have not yet reached enlightenment ...
>   A koan is incomplete.
> 
> Please meditate on the following code:
>    File "koans/asserts.lsp"
>    Koan "TEST-TRUE-OR-FALSE"
>    Current koan assert status is "(INCOMPLETE INCOMPLETE)"
> 
> You are now 0/175 koans and 0/27 lessons closer to reaching enlightenment

TEST-TRUE-OR-FALSE is the last koan of asserts.lsp

**Comment by acdart** [comment]
Yes

**Comment by skovsgaard** [comment]
This happens on SBCL too, however not for all koans. It does happen in assert.lsp though.

**Comment by allenu** [comment]
I'm hitting this as well with CLISP. It's frustrating writing solutions to each exercise in top-down order and then validating them in bottom-up order.

**Comment by fixermark** [comment]
Root issue is that the framework bundles the tests into a hash and then iterates over that hash to get test names:

https://github.com/google/lisp-koans/blob/35a520021fab4393b2565dd42ca9e626ac0951b7/lisp-unit.lsp#L716

Common Lisp hyperspec clairifies that the order of evaluation in common lisp for looping over hashes is undefined (http://www.lispworks.com/documentation/HyperSpec/Body/06_abaf.htm).

It appears that (at least on my machine configuration / common lisp version), replacing the `run-koans` method in `lisp-unit.lsp` with the following ameliorates the issue in practice, but this solution is itself implementation-dependent, and a real solution would involve reworking how the `lisp-unit.lsp` package manages the list of tests to treat it as a list, not a hashtable.



```
(defun run-koans (package)
  "Run the list of test thunks in the package. Stopping                                                                                       
   at a failure or incomplete, with more helpful messaging"
  (let ((tests (loop
                  with results = nil
                  for test-name being each hash-key in (package-table package)
                  using (hash-value unit-test)
                  do (push `(,test-name . ,unit-test) results)
                    finally (return results))))
    (loop

    with koan-results = nil
    for (test-name . unit-test) in tests
    if unit-test do
      (push (list test-name (koan-result (code unit-test))) koan-results)
    else do
      (push (list test-name :missing) koan-results)
    until (and (not *proceed-after-failure*) (any-non-pass-p koan-results))
    finally (return koan-results))))

```
