### ISSUE TITLE
Supposed mistake in koan special-forms.lsp

### ISSUE THREAD

**Issue by KZiemian** [google/lisp-koans#78]
I am sorry for posting things like that, I now start learning how to use GitHub. There is some way to send this code directly but I don't know how.

In special-froms.lsp there is a koan like that.

(define-test write-your-own-let-statement
  "fix the let statement to get the tests to pass"
  (setf a 100)
  (setf b 23)
  (setf c 456)
  (let ((a 0)
        (b __)
        (c __))
    (assert-equal a 100)
    (assert-equal b 200)
    (assert-equal c "Jellyfish"))
  (let* ((a 0))
    (assert-equal a 121)
    (assert-equal b 200)
    (assert-equal c (+ a (/ b a)))))

After thinkig about it and check one solution posted on GitHub I think that correct form is something like code bellow.
(define-test write-your-own-let-statement
  "fix the let statement to get the tests to pass"
  (setf a 100)
  (setf b 23)
  (setf c 456)
  (let ((a __)
        (b __)
        (c __))
    (assert-equal a 100)
    (assert-equal b 200)
    (assert-equal c "Jellyfish"))
  (let* ((a __)
	 (b __)
	 (c __))
    (assert-equal a 121)
    (assert-equal b 200)
    (assert-equal c (+ a (/ b a)))))

**Comment by Slids** [comment]
This has been fixed, so closed.
