### ISSUE TITLE
Error in vectors.lsp

### ISSUE THREAD

**Issue by jboyens** [google/lisp-koans#92]
Great work, but I think I found an error:

https://github.com/google/lisp-koans/blob/96e7659984532581978aafceddff434e3dd95d07/koans/vectors.lsp#L29

`(make-array '4 :element-type 'bit)` makes something like `#*0000` not `#*0011`

**Comment by joaomlneto** [comment]
Same here.
Should be `#*0000`

**Comment by phoe** [comment]
This test invokes undefined behaviour.

[CLHS MAKE-ARRAY](http://clhs.lisp.se/Body/f_mk_ar.htm) states:

> If initial-element is not supplied, the consequences of later reading an uninitialized element of new-array are undefined unless either initial-contents is supplied or displaced-to is non-nil. 

Therefore, `(make-array '4 :element-type 'bit)` is not guaranteed to return `#*0000`. According to the standard, it is allowed to return `#*1111` as well, as well as any 4-bit combination.
