### ISSUE TITLE
Can I port some tests over to Racket koans under different license?

### ISSUE THREAD

**Issue by zyrolasting** [google/lisp-koans#99]
Hey guys, thank you so much for this project. It was extremely helpful in giving me an introduction to Lisp family languages. The Racket ecosystem has been lacking koans and they are now [under development](https://github.com/zyrolasting/racket-koans).

It might be worth porting some non-CL specific koans from here over there, but I want to be sure I am respecting the license:  If Koans are copied from this repo and rewritten to fit its destination with a citation pointing back here, does that trigger the viral clause in Apache 2.0 or am I still free to use different terms for the racket-koans source? The GitHub summary seems to indicate that I can use different terms, but IANAL.

**Comment by bileschi** [comment]
I also am not a lawyer, but as the primary author of lisp-koans, I say go for it.  Please offer reasonable attribution back to lisp-koans, thanks.

**Comment by zyrolasting** [comment]
Appreciate it!
